name: build-and-release

on: push

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Build
        run: mvn clean package

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: target/MiMaDebugger.jar

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: Binary

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            MiMaDebugger.jar
